export const bangumi: string;
export const bilibili: string;
export const blog: string;
export const bluesky: string;
export const misskey: string;
export const steam: string;
export const x: string;
export const youtube: string;
export const xiaohongshu: string;
